version: 2

build:
  os: ubuntu-22.04  # Plus largement supporté
  tools:
    python: "3.10"   # Version plus commune pour TensorFlow

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true  # Active les checks qualité

python:
  install:
    - requirements: docs/requirements.txt  # Décommentez cette partie
    - method: pip
      path: .  # Installe votre package en mode editable

formats:
  - pdf  # Génère aussi une version PDF